name: SwapFaceAPI-Service-Prod-GPU

image_uri: 'reynoldoramas/anyscale-swapface:py3.10-devcu11.8-cudnn8-ray2.46.0'

cloud: ANYSCALE_CLOUD_4

compute_config:
  head_node:
    instance_type: e2-standard-4
    resources:
      CPU: 0
      GPU: 0
    flags: {}
  worker_nodes:
    - instance_type: g2-standard-8-nvidia-l4-1
      flags: {}
      name: '1xL4:8CPU-32GB'
      min_nodes: 1
      max_nodes: 2
      market_type: PREFER_SPOT
      #resources:
      #  CPU: 0
    - instance_type: e2-standard-4
      flags: {}
      name: 4CPU-4GB
      min_nodes: 1
      max_nodes: 4
      market_type: ON_DEMAND  
      resources:
        CUSTOM_CPU: 10000
  flags:
    allow-cross-zone-autoscaling: false
#    disable_nfs_mount: true
#    instance_ranking_strategy:
#      - ranker_type: custom_group_order
#        ranker_config:
#          enable_replacement: true
#          group_order:
#            - 4CPU-4GB
#            - 1xL4:8CPU-32GB

#runtime_env:
#  placement_group_strategy: PACK
#  placement_group_bundles:
#    - name: gpu_bundle
#      bundles:
#        - CPU: 8
#          GPU: 1
#    - name: cpu_bundle
#      bundles:
#        - CPU: 4

query_auth_token_enabled: true

logging_config: # (Optional) Configuration options for logging.
  encoding: JSON # JSON or TEXT.
  log_level: INFO
  enable_access_log: true

applications:
- name: SwapFaceAPI
  route_prefix: /
  import_path: app.api.main:app

  deployments:
  - name: APIIngress
    num_replicas: 1
    ray_actor_options:
      num_cpus: 1
      num_gpus: 0
      resources:
        CUSTOM_CPU: 0.001
      #placement_group_bundles: cpu_bundle
    max_ongoing_requests: 5000
      
  - name: FaceAnalyzer
    #num_replicas: 1
    ray_actor_options:
      #num_cpus: 0.2
      num_gpus: 0.099
      #placement_group_bundles: gpu_bundle
    max_ongoing_requests: 2
    autoscaling_config:
      target_ongoing_requests: 2
      min_replicas: 4
      initial_replicas: 4
      max_replicas: 500
      upscale_delay_s: 10
      downscale_delay_s: 300
      upscaling_factor: 1
      downscaling_factor: 0.5
      metrics_interval_s: 2
      look_back_period_s: 2

  - name: FaceSwapper
    #num_replicas: 1
    ray_actor_options:
      #num_cpus: 0.2
      num_gpus: 0.099
      #placement_group_bundles: gpu_bundle
    max_ongoing_requests: 2
    autoscaling_config:
      target_ongoing_requests: 2
      min_replicas: 2
      initial_replicas: 2
      max_replicas: 500
      upscale_delay_s: 10
      downscale_delay_s: 300
      upscaling_factor: 0.5
      downscaling_factor: 0.5
      metrics_interval_s: 2
      look_back_period_s: 2

  - name: FaceEnhancer
    #num_replicas: 1
    ray_actor_options:
      #num_cpus: 0.2
      num_gpus: 0.099
      #placement_group_bundles: gpu_bundle
    max_ongoing_requests: 2
    autoscaling_config:
      target_ongoing_requests: 2
      min_replicas: 2
      initial_replicas: 2
      max_replicas: 500
      upscale_delay_s: 10
      downscale_delay_s: 300
      upscaling_factor: 1
      downscaling_factor: 0.5
      metrics_interval_s: 2
      look_back_period_s: 2

  - name: CodeFormerEnhancer
    #num_replicas: 1
    ray_actor_options:
      #num_cpus: 1
      num_gpus: 0.2
      #placement_group_bundles: gpu_bundle
    max_ongoing_requests: 5
    autoscaling_config:
      target_ongoing_requests: 3
      min_replicas: 0
      initial_replicas: 0
      max_replicas: 500
      upscale_delay_s: 5
      downscale_delay_s: 300
      upscaling_factor: 0.5
      downscaling_factor: 1
      metrics_interval_s: 2
      look_back_period_s: 2

  - name: SwapProcessor
    num_replicas: 1
    ray_actor_options:
      num_cpus: 1
      num_gpus: 0
      resources:
        CUSTOM_CPU: 0.001
      #placement_group_bundles: cpu_bundle
    max_ongoing_requests: 5000
#    autoscaling_config:
#      target_ongoing_requests: 25
#      min_replicas: 1
#      initial_replicas: 1
#      max_replicas: 500
#      upscale_delay_s: 10
#      downscale_delay_s: 120
#      upscaling_factor: 1
#      downscaling_factor: 0.5
#      metrics_interval_s: 2
#      look_back_period_s: 20

  - name: BackgroundRemover
    ray_actor_options:
      num_gpus: 0.3
    max_ongoing_requests: 3
    autoscaling_config:
      target_ongoing_requests: 2
      min_replicas: 0
      initial_replicas: 0
      max_replicas: 5
      upscale_delay_s: 10
      downscale_delay_s: 60
      upscaling_factor: 1
      downscaling_factor: 1
      metrics_interval_s: 2
      look_back_period_s: 2

  - name: GCPImageManager
    #num_replicas: 1
    ray_actor_options:
      num_cpus: 0.15
      resources:
        CUSTOM_CPU: 0.001
      #num_gpus: 0
      #placement_group_bundles: cpu_bundle
    max_ongoing_requests: 3
    autoscaling_config:
      target_ongoing_requests: 1
      min_replicas: 10
      initial_replicas: 10
      max_replicas: 500
      upscale_delay_s: 10
      downscale_delay_s: 300
      upscaling_factor: 1
      downscaling_factor: 0.5
      metrics_interval_s: 2
      look_back_period_s: 2
    init_args:
          - app/configs/anyscale_bucket_credentials.json
          - anyscale_tmp_faces

excludes: # (Optional) List of files to exclude from being packaged up for the job.
  - .git
  - .env
  - .DS_Store
  - __pycache__
  #- app/configs/anyscale_bucket_credentials.json

http_options:
  request_timeout_s: 60 # (Optional) Timeout for HTTP requests in seconds. Default is no timeout.
  keep_alive_timeout_s: 300 # (Optional) Timeout for HTTP keep-alive connections in seconds. Default is 5 seconds.

ray_gcs_external_storage_config:
  enabled: false
