proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000
  #keep_alive_timeout_s: #

logging_config:
  encoding: JSON
  log_level: INFO
  logs_dir: null
  enable_access_log: true

applications:
- name: SwapFaceAPI
  route_prefix: /
  import_path: app.api.main:app
  runtime_env: {
    "pip": [
      "opencv-python-headless",
      "onnx",
      "onnxruntime",
      "python-multipart",
    ]
  }

  deployments:
  - name: APIIngress
    num_replicas: 1
    ray_actor_options:
      num_cpus: 0.15
      num_gpus: 0
    max_ongoing_requests: 200
      
  - name: FaceAnalyzer
    #num_replicas: 1
    ray_actor_options:
      num_cpus: 0.25
      num_gpus: 0
    max_ongoing_requests: 3
    autoscaling_config:
      target_ongoing_requests: 1
      min_replicas: 1
      initial_replicas: 1
      max_replicas: 50
      upscale_delay_s: 5
      downscale_delay_s: 300
      upscaling_factor: 1
      downscaling_factor: 1
      metrics_interval_s: 2
      look_back_period_s: 2

  - name: FaceSwapper
    #num_replicas: 1
    ray_actor_options:
      num_cpus: 1
      num_gpus: 0
    max_ongoing_requests: 3
    autoscaling_config:
      target_ongoing_requests: 1
      min_replicas: 1
      initial_replicas: 1
      max_replicas: 50
      upscale_delay_s: 5
      downscale_delay_s: 300
      upscaling_factor: 2
      downscaling_factor: 1
      metrics_interval_s: 2
      look_back_period_s: 2

  - name: FaceEnhancer
    #num_replicas: 1
    ray_actor_options:
      num_cpus: 1
      num_gpus: 0
    max_ongoing_requests: 3
    autoscaling_config:
      target_ongoing_requests: 1
      min_replicas: 1
      initial_replicas: 1
      max_replicas: 50
      upscale_delay_s: 5
      downscale_delay_s: 300
      upscaling_factor: 2
      downscaling_factor: 1
      metrics_interval_s: 2
      look_back_period_s: 2
  
  - name: CodeFormerEnhancer
    #num_replicas: 1
    ray_actor_options:
      num_cpus: 1
      num_gpus: 0
    max_ongoing_requests: 3
    autoscaling_config:
      target_ongoing_requests: 1
      min_replicas: 1
      initial_replicas: 1
      max_replicas: 50
      upscale_delay_s: 5
      downscale_delay_s: 300
      upscaling_factor: 2
      downscaling_factor: 1
      metrics_interval_s: 2
      look_back_period_s: 2

  - name: GCPImageManager
    #num_replicas: 1
    ray_actor_options:
      num_cpus: 0.1
      num_gpus: 0
    max_ongoing_requests: 3
    autoscaling_config:
      target_ongoing_requests: 1
      min_replicas: 1
      initial_replicas: 1
      max_replicas: 50
      upscale_delay_s: 5
      downscale_delay_s: 300
      upscaling_factor: 1
      downscaling_factor: 1
      metrics_interval_s: 2
      look_back_period_s: 2
    init_args:
          - app/configs/anyscale_bucket_credentials.json
          - anyscale_tmp_faces

  
