name: SwapFaceAPI-Service-Prod

applications:
- name: SwapFaceAPI
  route_prefix: /
  import_path: app.api.main:app
  runtime_env: {}  

  deployments:
  - name: APIIngress
    num_replicas: 1
    ray_actor_options:
      num_cpus: 0.15
      num_gpus: 0
    max_ongoing_requests: 200
      
  - name: FaceAnalyzer
    #num_replicas: 1
    ray_actor_options:
      num_cpus: 0.25
      num_gpus: 0
    max_ongoing_requests: 3
    autoscaling_config:
      target_ongoing_requests: 1
      min_replicas: 1
      initial_replicas: 1
      max_replicas: 50
      upscale_delay_s: 5
      downscale_delay_s: 300
      upscaling_factor: 1
      downscaling_factor: 1
      metrics_interval_s: 2
      look_back_period_s: 2

  - name: FaceSwapper
    #num_replicas: 1
    ray_actor_options:
      num_cpus: 1
      num_gpus: 0
    max_ongoing_requests: 3
    autoscaling_config:
      target_ongoing_requests: 1
      min_replicas: 1
      initial_replicas: 1
      max_replicas: 50
      upscale_delay_s: 5
      downscale_delay_s: 300
      upscaling_factor: 2
      downscaling_factor: 1
      metrics_interval_s: 2
      look_back_period_s: 2

  - name: FaceEnhancer
    #num_replicas: 1
    ray_actor_options:
      num_cpus: 1
      num_gpus: 0
    max_ongoing_requests: 3
    autoscaling_config:
      target_ongoing_requests: 1
      min_replicas: 1
      initial_replicas: 1
      max_replicas: 50
      upscale_delay_s: 5
      downscale_delay_s: 300
      upscaling_factor: 2
      downscaling_factor: 1
      metrics_interval_s: 2
      look_back_period_s: 2

  - name: GCPImageManager
    #num_replicas: 1
    ray_actor_options:
      num_cpus: 0.1
      num_gpus: 0
    max_ongoing_requests: 3
    autoscaling_config:
      target_ongoing_requests: 1
      min_replicas: 1
      initial_replicas: 1
      max_replicas: 50
      upscale_delay_s: 5
      downscale_delay_s: 300
      upscaling_factor: 1
      downscaling_factor: 1
      metrics_interval_s: 2
      look_back_period_s: 2
    init_args:
          - app/configs/anyscale_bucket_credentials.json
          - anyscale_tmp_faces

compute_config:
  head_node:
  instance_type: e2-highcpu-4

  worker_nodes:
  - instance_type: e2-standard-8
    min_nodes: 0
    max_nodes: 5
    market_type: PREFER_SPOT # (Optional) Defaults to ON_DEMAND

  enable_cross_zone_scaling: true # (Optional) Defaults to false.
  
excludes: # (Optional) List of files to exclude from being packaged up for the job.
  - .git
  - .env
  - .DS_Store
  - __pycache__
  #- app/configs/anyscale_bucket_credentials.json

query_auth_token_enabled: True # (Optional) Whether or not to gate this service behind an auth token.

http_options:
  port: 8000
  request_timeout_s: 60 # (Optional) Timeout for HTTP requests in seconds. Default is no timeout.
  keep_alive_timeout_s: 60 # (Optional) Timeout for HTTP keep-alive connections in seconds. Default is 5 seconds.

logging_config: # (Optional) Configuration options for logging.
  encoding: JSON # JSON or TEXT.
  log_level: INFO
  enable_access_log: true

ray_gcs_external_storage_config:
  enabled: false
