name: SwapFaceAPI-Service-Prod-GPU

image_uri: 'reynoldoramas/anyscale-swapface:py3.10-devcu11.8-cudnn8-ray2.46.0'

cloud: ANYSCALE_CLOUD_4

compute_config:
  head_node:
    instance_type: e2-standard-4
    resources:
      CPU: 0
      GPU: 0
    flags: {}
  worker_nodes:
    - instance_type: g2-standard-8-nvidia-l4-1
      flags: {}
      name: '1xL4:8CPU-32GB'
      min_nodes: 1
      max_nodes: 25
      market_type: PREFER_SPOT
    - instance_type: e2-highcpu-4
      flags: {}
      name: 4CPU-4GB
      min_nodes: 1
      max_nodes: 25
      market_type: PREFER_SPOT
  enable_cross_zone_scaling: false
  flags:
    allow-cross-zone-autoscaling: false

ray_version: 2.46.0

query_auth_token_enabled: true

logging_config:
  encoding: JSON
  log_level: INFO
  enable_access_log: true

http_options:
  request_timeout_s: 60
  keep_alive_timeout_s: 300

applications:
  - name: SwapFaceAPI
    route_prefix: /
    import_path: app.api.main:app
    deployments:
      - name: APIIngress
        num_replicas: 1
        ray_actor_options:
          num_cpus: 1
          num_gpus: 0
        max_ongoing_requests: 5000
      - name: FaceAnalyzer
        ray_actor_options:
          num_gpus: 0.1
        autoscaling_config:
          max_replicas: 500
          min_replicas: 5
          upscale_delay_s: 10
          initial_replicas: 5
          upscaling_factor: 1
          downscale_delay_s: 180
          downscaling_factor: 0.5
          look_back_period_s: 2
          metrics_interval_s: 2
          target_ongoing_requests: 2
        max_ongoing_requests: 2
      - name: FaceSwapper
        ray_actor_options:
          num_gpus: 0.1
        autoscaling_config:
          max_replicas: 500
          min_replicas: 2
          upscale_delay_s: 10
          initial_replicas: 2
          upscaling_factor: 0.5
          downscale_delay_s: 180
          downscaling_factor: 0.5
          look_back_period_s: 2
          metrics_interval_s: 2
          target_ongoing_requests: 2
        max_ongoing_requests: 2
      - name: FaceEnhancer
        ray_actor_options:
          num_gpus: 0.1
        autoscaling_config:
          max_replicas: 500
          min_replicas: 3
          upscale_delay_s: 10
          initial_replicas: 3
          upscaling_factor: 1
          downscale_delay_s: 180
          downscaling_factor: 0.5
          look_back_period_s: 2
          metrics_interval_s: 2
          target_ongoing_requests: 2
        max_ongoing_requests: 2
      - name: CodeFormerEnhancer
        ray_actor_options:
          num_gpus: 0.2
        autoscaling_config:
          max_replicas: 500
          min_replicas: 0
          upscale_delay_s: 10
          initial_replicas: 0
          upscaling_factor: 0.5
          downscale_delay_s: 180
          downscaling_factor: 1
          look_back_period_s: 2
          metrics_interval_s: 2
          target_ongoing_requests: 3
        max_ongoing_requests: 5
      - name: SwapProcessor
        num_replicas: 1
        ray_actor_options:
          num_cpus: 1
          num_gpus: 0
        max_ongoing_requests: 5000
      - name: GCPImageManager
        init_args:
          - app/configs/anyscale_bucket_credentials.json
          - anyscale_tmp_faces
        ray_actor_options:
          num_cpus: 0.1
          num_gpus: 0
        autoscaling_config:
          max_replicas: 500
          min_replicas: 5
          upscale_delay_s: 10
          initial_replicas: 10
          upscaling_factor: 1
          downscale_delay_s: 180
          downscaling_factor: 1
          look_back_period_s: 2
          metrics_interval_s: 2
          target_ongoing_requests: 1
        max_ongoing_requests: 5

excludes: # (Optional) List of files to exclude from being packaged up for the job.
  - .git
  - .env
  - .DS_Store
  - __pycache__
  #- app/configs/anyscale_bucket_credentials.json

ray_gcs_external_storage_config:
  enabled: false